# Generated by Django 5.1.1 on 2024-09-17 07:27

import datetime
import portfolios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('thumbnail', models.ImageField(upload_to=portfolios.models.unique_filename, verbose_name='Thumbnail')),
                ('cover_image', models.ImageField(upload_to=portfolios.models.unique_cover_filename, verbose_name='Cover Image')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(help_text='Short description for listing page', verbose_name='Short Description')),
                ('long_description', models.TextField(help_text='Long description in markdown format', verbose_name='Long Description')),
                ('date', models.DateField(default=datetime.date.today, help_text='Date when the project was completed', verbose_name='Date')),
                ('technologies', models.TextField(help_text='Comma-separated list of technologies', verbose_name='Technologies')),
                ('live_demo_url', models.URLField(blank=True, null=True, verbose_name='Live Demo URL')),
                ('source_code_url', models.URLField(blank=True, null=True, verbose_name='Source Code URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
