# Generated by Django 5.1.1 on 2024-09-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Development', 'Web Development'), ('App', 'Mobile App'), ('Other', 'Other')], default='dsf', max_length=100, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Client Name'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client_testimonial',
            field=models.TextField(blank=True, null=True, verbose_name='Client Testimonial'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Project Duration'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Completed', max_length=20, verbose_name='Project Status'),
        ),
    ]
