# Generated by Django 5.1.1 on 2024-09-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_portfolio_category_portfolio_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='client_testimonial',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='status',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Web Development'), ('app', 'Mobile App'), ('seo', 'SEO')], max_length=100, verbose_name='Category'),
        ),
    ]
