# Generated by Django 5.1.1 on 2024-09-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_remove_portfolio_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
