# Generated by Django 5.1.1 on 2024-09-08 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Date when the project was completed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=models.TextField(help_text='Long description in markdown format'),
        ),
    ]
