# Generated by Django 5.1.1 on 2024-09-08 11:13

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='dfg', upload_to=projects.models.unique_filename),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(upload_to=projects.models.unique_cover_filename),
        ),
    ]
