# Generated by Django 5.1.1 on 2024-09-08 11:15

import datetime
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_thumbnail_alter_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_eight',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.unique_filename, verbose_name='Image Eight'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.unique_filename, verbose_name='Image Five'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.unique_filename, verbose_name='Image Four'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.unique_filename, verbose_name='Image One'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_seven',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.unique_filename, verbose_name='Image Seven'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_six',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.unique_filename, verbose_name='Image Six'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.unique_filename, verbose_name='Image Three'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.unique_filename, verbose_name='Image Two'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(upload_to=projects.models.unique_cover_filename, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Date when the project was completed', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_demo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Live Demo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=models.TextField(help_text='Long description in markdown format', verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(help_text='Short description for listing page', verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_code_url',
            field=models.URLField(blank=True, null=True, verbose_name='Source Code URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.TextField(help_text='Comma-separated list of technologies', verbose_name='Technologies'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to=projects.models.unique_filename, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
