# Generated by Django 5.1.1 on 2024-09-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_image_eight_project_image_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_eight',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_five',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_seven',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_six',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_two',
        ),
    ]
