baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Rajarshi Samaddar"

[params]
    title = "Rajarshi Samaddar"
    description = "Developer, entrepreneur, and tech optimist. Founder & Lead Dev at Ridotech. Mentors junior developers and solves complex backend challenges."