# Generated by Django 5.1.1 on 2024-09-17 09:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('opportunity_type', models.CharField(choices=[('freelance', 'Freelance'), ('part_time', 'Part-Time'), ('full_time', 'Full-Time')], max_length=20)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('project_scope', models.TextField(blank=True, null=True)),
                ('estimated_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('desired_start_date', models.DateField()),
                ('how_heard', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('relevant_file', models.FileField(blank=True, null=True, upload_to=core.models.get_unique_file_name)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
