# Generated by Django 5.1.1 on 2024-09-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteData',
        ),
    ]
