# Generated by Django 5.1.1 on 2024-09-18 12:39

import blogs.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('thumbnail', models.ImageField(upload_to=blogs.models.unique_filename, verbose_name='Thumbnail')),
                ('cover_image', models.ImageField(upload_to=blogs.models.unique_cover_filename, verbose_name='Cover Image')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(help_text='Short description for listing page', verbose_name='Short Description')),
                ('long_description', models.TextField(help_text='Long description in markdown format', verbose_name='Long Description')),
                ('date', models.DateField(default=datetime.date.today, help_text='Date when the blog was completed', verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogcategory', verbose_name='Category')),
                ('tags', models.ManyToManyField(help_text='List of tags', to='blogs.tag', verbose_name='Tags')),
            ],
        ),
    ]
